languageCode = "de-de"
baseurl = "https://eldorado234.github.io/schulsportverein/"
title = "1. Wiesbadener Schulsportverein 1994 e.V."
theme = "schulsportverein"
publishdir = "docs"

[params]
	facebook = true
	cdn = true
	description = "Der 1. Wiesbadener Schulsportverein 1994 e.V. (WSV) ist ein schulbezogener Breitensportverein mit dem Schwerpunkt Radsport. Ein Verein f√ºr alle, egal was jemand kann oder wo er her kommt."

[[menu.secondary]]
    name = "Mitgliedsantrag (PDF)"
    weight = 40
    identifier = "mitgliedsantrag"
    url = "/schulsportverein-mitgliedsantrag.pdf"
