languageCode = "de-de"
baseurl = "https://eldorado234.github.io/schulsportverein/"
title = "1. Wiesbadener Schulsportverein 1994 e.V."
theme = "schulsportverein"
publishdir = "docs"

[params]
	cdn = true
    partner = true
	description = "Ein schulbezogener Breitensportverein mit dem Schwerpunkt Radsport. Ein Verein f√ºr alle, egal was jemand kann oder wo er her kommt."
    defaultHeader = "header/two.jpg"

[[menu.main]]
    name = "Tanzlaune"
    weight = 90
    identifier = "Tanzlaune"
    url = "https://tanzlaune.de/"

[[menu.secondary]]
    name = "Facebook"
    weight = -10
    identifier = "facebook"
    url = "https://www.facebook.com/schulsportverein/"

[[menu.secondary]]
    name = "Mitgliedsantrag (PDF)"
    weight = 40
    identifier = "mitgliedsantrag"
    url = "/schulsportverein-mitgliedsantrag.pdf"
